### ISSUE TITLE
v0.1.1 Promise Error

### ISSUE THREAD

**Issue by rbhr** [timcharper/homebridge-opensprinkler#2]
Hi Tim
After upgrading to v0.1.1, Homebridge doesn't start due to this error.

[2018-6-20 00:33:26] [OpenSprinkler] error while polling: TypeError: promise.finally is not a function
    at Promise (/homebridge/node_modules/homebridge-opensprinkler/index.js:24:20)
    at new Promise (<anonymous>)
    at withTimeoutCancellation (/homebridge/node_modules/homebridge-opensprinkler/index.js:19:10)
    at SprinklerPlatform.poll (/homebridge/node_modules/homebridge-opensprinkler/index.js:147:16)
    at openSprinklerApi.getStatus.then (/homebridge/node_modules/homebridge-opensprinkler/index.js:134:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:437) UnhandledPromiseRejectionWarning: TypeError: done.finally is not a function
    at SprinklerPlatform.poll (/homebridge/node_modules/homebridge-opensprinkler/index.js:167:17)
    at openSprinklerApi.getStatus.then (/homebridge/node_modules/homebridge-opensprinkler/index.js:134:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:437) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by calanish** [comment]
FWIW I just updated to v0.1.1 and have had no issues.

pi@PiBridge:~ $ npm --version 
6.1.0
pi@PiBridge:~ $  nodejs --version 
v10.4.1
pi@PiBridge:~ $

**Comment by rbhr** [comment]
Same versions as you @calanish

**Comment by timcharper** [comment]
Yeah :) Glad you found it. I'll add the node version requirement in the README.
